### ISSUE TITLE
"Unexpected input" error for input listed by ml-spec

### ISSUE THREAD

**Issue by tsgouvea** [flatironinstitute/mountainlab-js#18]
Input _file_in_ is listed for processor _kepecs.duplifile_. Yet, ml-run-process throws a "Unexpected input: file_in" error.

I might be doing something wrong (eg. exe_command is possibly flawed - see issue #16) - help appreciated.

Spec file created with [jsonlab](https://github.com/fangq/jsonlab/tree/474d8c824800b5f2109c08f989085cb961acdbe3).
Original code [here](https://github.com/tsgouvea/mp_minim/tree/53842439332849492d35c60f9ff66d9c3877ff57).

```
(mycondaenv) computername:~ username$ ml-spec kepecs.duplifile
{
    "name": "kepecs.duplifile",
    "version": "0.0",
    "description": "Duplicates input file",
    "inputs": {
        "name": "file_in",
        "optional": 0
    },
    "outputs": [],
    "parameters": [],
    "opts": {
        "force_run": 1
    },
    "exe_command": "/Users/username/.mountainlab/packages/minim/run_mfile.sh \"cd('processors'), duplifile($file_in$)\""
}
(mycondaenv) computername:~ username$ ml-run-process kepecs.duplifile --inputs file_in:"/Users/username/Downloads/geom.csv"
[ Getting processor spec... ]
Error: Unexpected input: file_in
    at check_iop (/Users/username/Programs/mountainlab-js/mlproc/run_process.js:906:10)
    at run_process_2 (/Users/username/Programs/mountainlab-js/mlproc/run_process.js:47:3)
    at /Users/username/Programs/mountainlab-js/mlproc/run_process.js:29:3
    at /Users/username/Programs/mountainlab-js/mlproc/common.js:72:7
    at /Users/username/Programs/mountainlab-js/mlproc/common.js:226:6
    at /Users/username/Programs/mountainlab-js/mlproc/db_utils.js:65:4
    at result (/Users/username/Programs/mountainlab-js/mlproc/node_modules/mongodb/lib/utils.js:414:17)
    at session.endSession (/Users/username/Programs/mountainlab-js/mlproc/node_modules/mongodb/lib/utils.js:401:11)
    at ClientSession.endSession (/Users/username/Programs/mountainlab-js/mlproc/node_modules/mongodb/node_modules/mongodb-core/lib/sessions.js:104:41)
    at executeCallback (/Users/username/Programs/mountainlab-js/mlproc/node_modules/mongodb/lib/utils.js:397:17)
Unexpected input: file_in
(mycondaenv) computername:~ username$ 
```

**Comment by alexmorley** [comment]
"inputs" needs to be an array of objects e.g.

``` js
{
    "name": "kepecs.duplifile",
    "version": "0.0",
    "description": "Duplicates input file",
    "inputs": [  //square bracket here important
{
        "name": "file_in",
        "optional": 0
    }
], //square bracket here important
    "outputs": [],
    "parameters": [],
    "opts": {
        "force_run": 1
    },
    "exe_command": "/Users/username/.mountainlab/packages/minim/run_mfile.sh \"cd('processors'), duplifile($file_in$)\""
}

```

**Comment by alexmorley** [comment]
This means that we can allow as many inputs as we want :)

**Comment by tsgouvea** [comment]
That was it - it works now, code below
[https://github.com/tsgouvea/ml_identity_matlab](https://github.com/tsgouvea/ml_identity_matlab)
Closing issue.
