### ISSUE TITLE
Trying to install but failing

### ISSUE THREAD

**Issue by cafalchio** [flatironinstitute/mountainlab-js#85]
I have tried to install using both conda and npm in both ubuntu 20.04 and 18.04 both inside WLS2. 
My current node is v16.14.0. (error below), But I have tried to remove ubuntu and starting from a clean system. I think I have been trying to install for a couple of days.

Is there a slack channel for the mountainsort/mountainlab?

ml-list-processors > give the output.
/usr/lib/node_modules/mountainlab/mlproc/list_processors.js:3
var matcher = require('matcher')
              ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/lib/node_modules/mountainlab/node_modules/matcher/index.js from /usr/lib/node_modules/mountainlab/mlproc/list_processors.js not supported.
Instead change the require of index.js in /usr/lib/node_modules/mountainlab/mlproc/list_processors.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/usr/lib/node_modules/mountainlab/mlproc/list_processors.js:3:15)
    at Command.<anonymous> (/usr/lib/node_modules/mountainlab/mlproc/mlproc:39:5)
    at Command.listener (/usr/lib/node_modules/mountainlab/node_modules/commander/index.js:315:8)
    at Command.emit (node:events:520:28)
    at Command.parseArgs (/usr/lib/node_modules/mountainlab/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/lib/node_modules/mountainlab/node_modules/commander/index.js:474:21)
    at main (/usr/lib/node_modules/mountainlab/mlproc/mlproc:193:11) {
  code: 'ERR_REQUIRE_ESM'

**Comment by eintzandt** [comment]
I am also having issues installing using conda on both a Windows PC and a Mac (M2 chip). On both systems, I am getting the PackagesNotFoundError after running "conda install -c flatiron -c conda-forge mountainlab" in my mountainlab environment
